weights: ./models/epoch40_model.pt

# feeder
feeder: feeder.feeder.Feeder
test_feeder_args:
   data_path: data/My/38A_data.npy
   label_path: data/My/38A_label.pkl

#  data_path: ./data/Kinetics/kinetics-skeleton/val_data.npy
#  label_path: ./data/Kinetics/kinetics-skeleton/val_label.pkl

# model
model: net.st_gcn.Model
model_args:
  in_channels: 3
  num_class: 2
  edge_importance_weighting: True
  graph_args:
    layout: 'alphapose'
    strategy: 'spatial'

# test 
phase: test
device: 0
test_batch_size: 1
