work_dir: ./work_dir/recognition/kinetics_skeleton/SAFA_GCN_TOPK

# feeder
feeder: feeder.feeder.Feeder
train_feeder_args:
  random_choose: True
  random_move: True
  window_size: 6000 
  data_path: data/My/12A_data.npy
  label_path: data/My/12A_label.pkl
test_feeder_args:
  data_path: data/My/38A_data.npy
  label_path: data/My/38A_label.pkl


# supervised model
# model: net.safa_gcn_twostream.Model
# top-K model
model: net.safa_gcn_twostream_topk.Model

model_args:
  in_channels: 3
  num_class: 2
  edge_importance_weighting: True
  graph_args:
    layout: 'alphapose'
    strategy: 'spatial'
  kappa: 2

# training
device: [0]
batch_size: 1
test_batch_size: 1

#optim
base_lr: 0.000001
step: [100,200,300,400,500]
num_epoch: 5




