# command line: main.py recognition -c config/safa_gcn/kinetics-skeleton/train.yaml

base_lr: 1.0e-06
batch_size: 1
config: config/safa_gcn/kinetics-skeleton/train.yaml
debug: false
device:
- 0
eval_interval: 5
feeder: feeder.feeder.Feeder
ignore_weights: []
log_interval: 100
model: net.safa_gcn_twostream_topk.Model
model_args:
    edge_importance_weighting: true
    graph_args:
        layout: alphapose
        strategy: spatial
    in_channels: 3
    kappa: 2
    num_class: 2
nesterov: true
num_epoch: 5
num_worker: 4
optimizer: SGD
pavi_log: false
phase: train
print_log: true
save_interval: 10
save_log: true
save_result: false
show_topk:
- 1
- 1
start_epoch: 0
step:
- 100
- 200
- 300
- 400
- 500
test_batch_size: 1
test_feeder_args:
    data_path: data/My/38A_data.npy
    label_path: data/My/38A_label.pkl
train_feeder_args:
    data_path: data/My/12A_data.npy
    label_path: data/My/12A_label.pkl
    random_choose: true
    random_move: true
    window_size: 6000
use_gpu: true
weight_decay: 0.1
weights: null
work_dir: ./work_dir/recognition/kinetics_skeleton/SAFA_GCN_TOPK
